/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartCityDSLScopeProvider extends DelegatingScopeProvider {
}
