/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmartCityDSLStandaloneSetup extends SmartCityDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SmartCityDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
