/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmartCityDSLRuntimeModule extends AbstractSmartCityDSLRuntimeModule {
}
