/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import smartcity.project.xtext.ide.contentassist.antlr.internal.InternalSmartCityDSLParser;
import smartcity.project.xtext.services.SmartCityDSLGrammarAccess;

public class SmartCityDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SmartCityDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SmartCityDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSourceAccess().getAlternatives(), "rule__Source__Alternatives");
			builder.put(grammarAccess.getDataAccess().getAlternatives(), "rule__Data__Alternatives");
			builder.put(grammarAccess.getInfrastructureComponentAccess().getAlternatives(), "rule__InfrastructureComponent__Alternatives");
			builder.put(grammarAccess.getIoTDevAccess().getAlternatives(), "rule__IoTDev__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getSmartCityModelAccess().getGroup(), "rule__SmartCityModel__Group__0");
			builder.put(grammarAccess.getSmartCityModelAccess().getGroup_1(), "rule__SmartCityModel__Group_1__0");
			builder.put(grammarAccess.getSmartCityModelAccess().getGroup_1_3(), "rule__SmartCityModel__Group_1_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup(), "rule__SmartCity__Group__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_1(), "rule__SmartCity__Group_1__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_3(), "rule__SmartCity__Group_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_3_3(), "rule__SmartCity__Group_3_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4(), "rule__SmartCity__Group_4__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4_3(), "rule__SmartCity__Group_4_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_5(), "rule__SmartCity__Group_5__0");
			builder.put(grammarAccess.getDataPackageAccess().getGroup(), "rule__DataPackage__Group__0");
			builder.put(grammarAccess.getDataPackageAccess().getGroup_4(), "rule__DataPackage__Group_4__0");
			builder.put(grammarAccess.getDataPackageAccess().getGroup_4_1(), "rule__DataPackage__Group_4_1__0");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getGroup(), "rule__PublicInfrastructureLayer__Group__0");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getGroup_3(), "rule__PublicInfrastructureLayer__Group_3__0");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getGroup_3_3(), "rule__PublicInfrastructureLayer__Group_3_3__0");
			builder.put(grammarAccess.getSocialMediaAccess().getGroup(), "rule__SocialMedia__Group__0");
			builder.put(grammarAccess.getSocialMediaAccess().getGroup_4(), "rule__SocialMedia__Group_4__0");
			builder.put(grammarAccess.getOpenDataAccess().getGroup(), "rule__OpenData__Group__0");
			builder.put(grammarAccess.getOpenDataAccess().getGroup_4(), "rule__OpenData__Group_4__0");
			builder.put(grammarAccess.getProvidedDataAccess().getGroup(), "rule__ProvidedData__Group__0");
			builder.put(grammarAccess.getProvidedDataAccess().getGroup_3(), "rule__ProvidedData__Group_3__0");
			builder.put(grammarAccess.getProvidedDataAccess().getGroup_3_1(), "rule__ProvidedData__Group_3_1__0");
			builder.put(grammarAccess.getStakeholderAccess().getGroup(), "rule__Stakeholder__Group__0");
			builder.put(grammarAccess.getStakeholderAccess().getGroup_3(), "rule__Stakeholder__Group_3__0");
			builder.put(grammarAccess.getRealValueAccess().getGroup(), "rule__RealValue__Group__0");
			builder.put(grammarAccess.getBoolValueAccess().getGroup(), "rule__BoolValue__Group__0");
			builder.put(grammarAccess.getIntegerValueAccess().getGroup(), "rule__IntegerValue__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getInfrastructureComponent_ImplAccess().getGroup(), "rule__InfrastructureComponent_Impl__Group__0");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getGroup(), "rule__MonitoringInfrastructure__Group__0");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getGroup_4(), "rule__MonitoringInfrastructure__Group_4__0");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getGroup_4_1(), "rule__MonitoringInfrastructure__Group_4_1__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_3(), "rule__Sensor__Group_3__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_3(), "rule__Actuator__Group_3__0");
			builder.put(grammarAccess.getSmartCityModelAccess().getSmartCitiesAssignment_1_2(), "rule__SmartCityModel__SmartCitiesAssignment_1_2");
			builder.put(grammarAccess.getSmartCityModelAccess().getSmartCitiesAssignment_1_3_1(), "rule__SmartCityModel__SmartCitiesAssignment_1_3_1");
			builder.put(grammarAccess.getSmartCityAccess().getCityAssignment_1_1(), "rule__SmartCity__CityAssignment_1_1");
			builder.put(grammarAccess.getSmartCityAccess().getStakeholdersAssignment_3_2(), "rule__SmartCity__StakeholdersAssignment_3_2");
			builder.put(grammarAccess.getSmartCityAccess().getStakeholdersAssignment_3_3_1(), "rule__SmartCity__StakeholdersAssignment_3_3_1");
			builder.put(grammarAccess.getSmartCityAccess().getDataAssignment_4_2(), "rule__SmartCity__DataAssignment_4_2");
			builder.put(grammarAccess.getSmartCityAccess().getDataAssignment_4_3_1(), "rule__SmartCity__DataAssignment_4_3_1");
			builder.put(grammarAccess.getSmartCityAccess().getInfrastructurelayerAssignment_5_1(), "rule__SmartCity__InfrastructurelayerAssignment_5_1");
			builder.put(grammarAccess.getDataPackageAccess().getNameAssignment_2(), "rule__DataPackage__NameAssignment_2");
			builder.put(grammarAccess.getDataPackageAccess().getDataAssignment_4_0(), "rule__DataPackage__DataAssignment_4_0");
			builder.put(grammarAccess.getDataPackageAccess().getDataAssignment_4_1_1(), "rule__DataPackage__DataAssignment_4_1_1");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getNameAssignment_1(), "rule__PublicInfrastructureLayer__NameAssignment_1");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getComponentsAssignment_3_2(), "rule__PublicInfrastructureLayer__ComponentsAssignment_3_2");
			builder.put(grammarAccess.getPublicInfrastructureLayerAccess().getComponentsAssignment_3_3_1(), "rule__PublicInfrastructureLayer__ComponentsAssignment_3_3_1");
			builder.put(grammarAccess.getSocialMediaAccess().getNameAssignment_2(), "rule__SocialMedia__NameAssignment_2");
			builder.put(grammarAccess.getSocialMediaAccess().getUrlAssignment_4_2(), "rule__SocialMedia__UrlAssignment_4_2");
			builder.put(grammarAccess.getOpenDataAccess().getNameAssignment_2(), "rule__OpenData__NameAssignment_2");
			builder.put(grammarAccess.getOpenDataAccess().getUrlAssignment_4_2(), "rule__OpenData__UrlAssignment_4_2");
			builder.put(grammarAccess.getProvidedDataAccess().getProviderAssignment_3_0(), "rule__ProvidedData__ProviderAssignment_3_0");
			builder.put(grammarAccess.getProvidedDataAccess().getProviderAssignment_3_1_1(), "rule__ProvidedData__ProviderAssignment_3_1_1");
			builder.put(grammarAccess.getStakeholderAccess().getNameAssignment_2(), "rule__Stakeholder__NameAssignment_2");
			builder.put(grammarAccess.getStakeholderAccess().getOrganizationAssignment_3_1(), "rule__Stakeholder__OrganizationAssignment_3_1");
			builder.put(grammarAccess.getRealValueAccess().getNameAssignment_2(), "rule__RealValue__NameAssignment_2");
			builder.put(grammarAccess.getRealValueAccess().getValueAssignment_4(), "rule__RealValue__ValueAssignment_4");
			builder.put(grammarAccess.getRealValueAccess().getUnitAssignment_6(), "rule__RealValue__UnitAssignment_6");
			builder.put(grammarAccess.getRealValueAccess().getSrcAssignment_9(), "rule__RealValue__SrcAssignment_9");
			builder.put(grammarAccess.getBoolValueAccess().getNameAssignment_2(), "rule__BoolValue__NameAssignment_2");
			builder.put(grammarAccess.getBoolValueAccess().getValueAssignment_4(), "rule__BoolValue__ValueAssignment_4");
			builder.put(grammarAccess.getBoolValueAccess().getUnitAssignment_6(), "rule__BoolValue__UnitAssignment_6");
			builder.put(grammarAccess.getBoolValueAccess().getSrcAssignment_9(), "rule__BoolValue__SrcAssignment_9");
			builder.put(grammarAccess.getIntegerValueAccess().getNameAssignment_2(), "rule__IntegerValue__NameAssignment_2");
			builder.put(grammarAccess.getIntegerValueAccess().getValueAssignment_4(), "rule__IntegerValue__ValueAssignment_4");
			builder.put(grammarAccess.getIntegerValueAccess().getUnitAssignment_6(), "rule__IntegerValue__UnitAssignment_6");
			builder.put(grammarAccess.getIntegerValueAccess().getSrcAssignment_9(), "rule__IntegerValue__SrcAssignment_9");
			builder.put(grammarAccess.getInfrastructureComponent_ImplAccess().getNameAssignment_2(), "rule__InfrastructureComponent_Impl__NameAssignment_2");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getNameAssignment_2(), "rule__MonitoringInfrastructure__NameAssignment_2");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getDevicesAssignment_4_0(), "rule__MonitoringInfrastructure__DevicesAssignment_4_0");
			builder.put(grammarAccess.getMonitoringInfrastructureAccess().getDevicesAssignment_4_1_1(), "rule__MonitoringInfrastructure__DevicesAssignment_4_1_1");
			builder.put(grammarAccess.getSensorAccess().getModelAssignment_2(), "rule__Sensor__ModelAssignment_2");
			builder.put(grammarAccess.getSensorAccess().getLocationAssignment_3_3(), "rule__Sensor__LocationAssignment_3_3");
			builder.put(grammarAccess.getActuatorAccess().getModelAssignment_2(), "rule__Actuator__ModelAssignment_2");
			builder.put(grammarAccess.getActuatorAccess().getLocationAssignment_3_3(), "rule__Actuator__LocationAssignment_3_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SmartCityDSLGrammarAccess grammarAccess;

	@Override
	protected InternalSmartCityDSLParser createParser() {
		InternalSmartCityDSLParser result = new InternalSmartCityDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SmartCityDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartCityDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
