/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import smartcity.project.xtext.ui.internal.XtextActivator;

public class SmartCityDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("smartcity.project.xtext.SmartCityDSL");
	}

}
