/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSmartCityDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.gssi.it/smartcity"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.gssi.it/smartcity/dataanalytics"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.gssi.it/smartcity/infrastructure"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.gssi.it/smartcity/stakeholder"));
		return result;
	}
}
