/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmartCityDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("smartcity/project/xtext/parser/antlr/internal/InternalSmartCityDSL.tokens");
	}
}
