/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import smartcity.project.xtext.parser.antlr.internal.InternalSmartCityDSLParser;
import smartcity.project.xtext.services.SmartCityDSLGrammarAccess;

public class SmartCityDSLParser extends AbstractAntlrParser {

	@Inject
	private SmartCityDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartCityDSLParser createParser(XtextTokenStream stream) {
		return new InternalSmartCityDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmartCityModel";
	}

	public SmartCityDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartCityDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
