/*
 * generated by Xtext 2.19.0
 */
package smartcity.project.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SmartCityDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SmartCityModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.SmartCityModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSmartCityModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSmartCitiesKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cSmartCitiesAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cSmartCitiesSmartCityParserRuleCall_1_2_0 = (RuleCall)cSmartCitiesAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cSmartCitiesAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cSmartCitiesSmartCityParserRuleCall_1_3_1_0 = (RuleCall)cSmartCitiesAssignment_1_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		////import "http://cs.gssi.it/smartcity/stakeholder" as stakeholder
		////import "http://cs.gssi.it/smartcity/infrastructure" as infrastructure
		////import "http://cs.gssi.it/smartcity" as smartcity
		//SmartCityModel smartcity::SmartCityModel:
		//	{smartcity::SmartCityModel} ('smartCities' '{' smartCities+=SmartCity ("," smartCities+=SmartCity)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{smartcity::SmartCityModel} ('smartCities' '{' smartCities+=SmartCity ("," smartCities+=SmartCity)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{smartcity::SmartCityModel}
		public Action getSmartCityModelAction_0() { return cSmartCityModelAction_0; }
		
		//('smartCities' '{' smartCities+=SmartCity ("," smartCities+=SmartCity)* '}')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'smartCities'
		public Keyword getSmartCitiesKeyword_1_0() { return cSmartCitiesKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_1() { return cLeftCurlyBracketKeyword_1_1; }
		
		//smartCities+=SmartCity
		public Assignment getSmartCitiesAssignment_1_2() { return cSmartCitiesAssignment_1_2; }
		
		//SmartCity
		public RuleCall getSmartCitiesSmartCityParserRuleCall_1_2_0() { return cSmartCitiesSmartCityParserRuleCall_1_2_0; }
		
		//("," smartCities+=SmartCity)*
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//","
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }
		
		//smartCities+=SmartCity
		public Assignment getSmartCitiesAssignment_1_3_1() { return cSmartCitiesAssignment_1_3_1; }
		
		//SmartCity
		public RuleCall getSmartCitiesSmartCityParserRuleCall_1_3_1_0() { return cSmartCitiesSmartCityParserRuleCall_1_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_4() { return cRightCurlyBracketKeyword_1_4; }
	}
	public class SourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.Source");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSocialMediaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOpenDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProvidedDataParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cStakeholderParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Source dataanalytics::Source:
		//	SocialMedia | OpenData | ProvidedData | Stakeholder;
		@Override public ParserRule getRule() { return rule; }
		
		//SocialMedia | OpenData | ProvidedData | Stakeholder
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SocialMedia
		public RuleCall getSocialMediaParserRuleCall_0() { return cSocialMediaParserRuleCall_0; }
		
		//OpenData
		public RuleCall getOpenDataParserRuleCall_1() { return cOpenDataParserRuleCall_1; }
		
		//ProvidedData
		public RuleCall getProvidedDataParserRuleCall_2() { return cProvidedDataParserRuleCall_2; }
		
		//Stakeholder
		public RuleCall getStakeholderParserRuleCall_3() { return cStakeholderParserRuleCall_3; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRealValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBoolValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntegerValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Data dataanalytics::Data:
		//	RealValue | BoolValue | IntegerValue;
		@Override public ParserRule getRule() { return rule; }
		
		//RealValue | BoolValue | IntegerValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RealValue
		public RuleCall getRealValueParserRuleCall_0() { return cRealValueParserRuleCall_0; }
		
		//BoolValue
		public RuleCall getBoolValueParserRuleCall_1() { return cBoolValueParserRuleCall_1; }
		
		//IntegerValue
		public RuleCall getIntegerValueParserRuleCall_2() { return cIntegerValueParserRuleCall_2; }
	}
	public class InfrastructureComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.InfrastructureComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInfrastructureComponent_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMonitoringInfrastructureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//InfrastructureComponent infrastructure::InfrastructureComponent:
		//	InfrastructureComponent_Impl | MonitoringInfrastructure;
		@Override public ParserRule getRule() { return rule; }
		
		//InfrastructureComponent_Impl | MonitoringInfrastructure
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//InfrastructureComponent_Impl
		public RuleCall getInfrastructureComponent_ImplParserRuleCall_0() { return cInfrastructureComponent_ImplParserRuleCall_0; }
		
		//MonitoringInfrastructure
		public RuleCall getMonitoringInfrastructureParserRuleCall_1() { return cMonitoringInfrastructureParserRuleCall_1; }
	}
	public class IoTDevElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.IoTDev");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSensorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cActuatorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//IoTDev infrastructure::IoTDev:
		//	Sensor | Actuator;
		@Override public ParserRule getRule() { return rule; }
		
		//Sensor | Actuator
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Sensor
		public RuleCall getSensorParserRuleCall_0() { return cSensorParserRuleCall_0; }
		
		//Actuator
		public RuleCall getActuatorParserRuleCall_1() { return cActuatorParserRuleCall_1; }
	}
	public class SmartCityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.SmartCity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSmartCityAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCityKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cCityAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cCityEStringParserRuleCall_1_1_0 = (RuleCall)cCityAssignment_1_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStakeholdersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cStakeholdersAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStakeholdersSourceParserRuleCall_3_2_0 = (RuleCall)cStakeholdersAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cStakeholdersAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cStakeholdersSourceParserRuleCall_3_3_1_0 = (RuleCall)cStakeholdersAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataDataPackageParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataDataPackageParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInfrastructurelayerKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInfrastructurelayerAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInfrastructurelayerPublicInfrastructureLayerParserRuleCall_5_1_0 = (RuleCall)cInfrastructurelayerAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SmartCity smartcity::SmartCity:
		//	{smartcity::SmartCity} ('city' city=EString)?
		//	'{' ('stakeholders' '{' stakeholders+=Source ("," stakeholders+=Source)* '}')? ('data' '{' data+=DataPackage (","
		//	data+=DataPackage)* '}')? ('infrastructurelayer' infrastructurelayer=PublicInfrastructureLayer)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{smartcity::SmartCity} ('city' city=EString)? '{' ('stakeholders' '{' stakeholders+=Source ("," stakeholders+=Source)*
		//'}')? ('data' '{' data+=DataPackage ("," data+=DataPackage)* '}')? ('infrastructurelayer'
		//infrastructurelayer=PublicInfrastructureLayer)? '}'
		public Group getGroup() { return cGroup; }
		
		//{smartcity::SmartCity}
		public Action getSmartCityAction_0() { return cSmartCityAction_0; }
		
		//('city' city=EString)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'city'
		public Keyword getCityKeyword_1_0() { return cCityKeyword_1_0; }
		
		//city=EString
		public Assignment getCityAssignment_1_1() { return cCityAssignment_1_1; }
		
		//EString
		public RuleCall getCityEStringParserRuleCall_1_1_0() { return cCityEStringParserRuleCall_1_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('stakeholders' '{' stakeholders+=Source ("," stakeholders+=Source)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'stakeholders'
		public Keyword getStakeholdersKeyword_3_0() { return cStakeholdersKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//stakeholders+=Source
		public Assignment getStakeholdersAssignment_3_2() { return cStakeholdersAssignment_3_2; }
		
		//Source
		public RuleCall getStakeholdersSourceParserRuleCall_3_2_0() { return cStakeholdersSourceParserRuleCall_3_2_0; }
		
		//("," stakeholders+=Source)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//stakeholders+=Source
		public Assignment getStakeholdersAssignment_3_3_1() { return cStakeholdersAssignment_3_3_1; }
		
		//Source
		public RuleCall getStakeholdersSourceParserRuleCall_3_3_1_0() { return cStakeholdersSourceParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('data' '{' data+=DataPackage ("," data+=DataPackage)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//data+=DataPackage
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//DataPackage
		public RuleCall getDataDataPackageParserRuleCall_4_2_0() { return cDataDataPackageParserRuleCall_4_2_0; }
		
		//("," data+=DataPackage)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=DataPackage
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//DataPackage
		public RuleCall getDataDataPackageParserRuleCall_4_3_1_0() { return cDataDataPackageParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('infrastructurelayer' infrastructurelayer=PublicInfrastructureLayer)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'infrastructurelayer'
		public Keyword getInfrastructurelayerKeyword_5_0() { return cInfrastructurelayerKeyword_5_0; }
		
		//infrastructurelayer=PublicInfrastructureLayer
		public Assignment getInfrastructurelayerAssignment_5_1() { return cInfrastructurelayerAssignment_5_1; }
		
		//PublicInfrastructureLayer
		public RuleCall getInfrastructurelayerPublicInfrastructureLayerParserRuleCall_5_1_0() { return cInfrastructurelayerPublicInfrastructureLayerParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DataPackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.DataPackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDataPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cDataAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cDataDataParserRuleCall_4_0_0 = (RuleCall)cDataAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cDataAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_1_1_0 = (RuleCall)cDataAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DataPackage dataanalytics::DataPackage:
		//	{dataanalytics::DataPackage}
		//	'dataPackage'
		//	name=EString
		//	'{' (data+=Data ("," data+=Data)*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::DataPackage} 'dataPackage' name=EString '{' (data+=Data ("," data+=Data)*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::DataPackage}
		public Action getDataPackageAction_0() { return cDataPackageAction_0; }
		
		//'dataPackage'
		public Keyword getDataPackageKeyword_1() { return cDataPackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(data+=Data ("," data+=Data)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//data+=Data
		public Assignment getDataAssignment_4_0() { return cDataAssignment_4_0; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_0_0() { return cDataDataParserRuleCall_4_0_0; }
		
		//("," data+=Data)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_1_1() { return cDataAssignment_4_1_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_1_1_0() { return cDataDataParserRuleCall_4_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PublicInfrastructureLayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.PublicInfrastructureLayer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPublicInfrastructureLayerAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cComponentsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cComponentsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cComponentsInfrastructureComponentParserRuleCall_3_2_0 = (RuleCall)cComponentsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cComponentsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cComponentsInfrastructureComponentParserRuleCall_3_3_1_0 = (RuleCall)cComponentsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PublicInfrastructureLayer infrastructure::PublicInfrastructureLayer:
		//	{infrastructure::PublicInfrastructureLayer} name=EString
		//	'{' ('components' '{' components+=InfrastructureComponent ("," components+=InfrastructureComponent)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{infrastructure::PublicInfrastructureLayer} name=EString '{' ('components' '{' components+=InfrastructureComponent (","
		//components+=InfrastructureComponent)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{infrastructure::PublicInfrastructureLayer}
		public Action getPublicInfrastructureLayerAction_0() { return cPublicInfrastructureLayerAction_0; }
		
		////	'PublicInfrastructureLayer'
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('components' '{' components+=InfrastructureComponent ("," components+=InfrastructureComponent)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'components'
		public Keyword getComponentsKeyword_3_0() { return cComponentsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//components+=InfrastructureComponent
		public Assignment getComponentsAssignment_3_2() { return cComponentsAssignment_3_2; }
		
		//InfrastructureComponent
		public RuleCall getComponentsInfrastructureComponentParserRuleCall_3_2_0() { return cComponentsInfrastructureComponentParserRuleCall_3_2_0; }
		
		//("," components+=InfrastructureComponent)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//components+=InfrastructureComponent
		public Assignment getComponentsAssignment_3_3_1() { return cComponentsAssignment_3_3_1; }
		
		//InfrastructureComponent
		public RuleCall getComponentsInfrastructureComponentParserRuleCall_3_3_1_0() { return cComponentsInfrastructureComponentParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SocialMediaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.SocialMedia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSocialMediaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSocialMediaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUrlKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUrlAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cUrlEStringParserRuleCall_4_2_0 = (RuleCall)cUrlAssignment_4_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SocialMedia dataanalytics::SocialMedia:
		//	{dataanalytics::SocialMedia}
		//	'socialMedia' name=EString '[' ('url' ':' url=EString)? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::SocialMedia} 'socialMedia' name=EString '[' ('url' ':' url=EString)? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::SocialMedia}
		public Action getSocialMediaAction_0() { return cSocialMediaAction_0; }
		
		//'socialMedia'
		public Keyword getSocialMediaKeyword_1() { return cSocialMediaKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//('url' ':' url=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'url'
		public Keyword getUrlKeyword_4_0() { return cUrlKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//url=EString
		public Assignment getUrlAssignment_4_2() { return cUrlAssignment_4_2; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_4_2_0() { return cUrlEStringParserRuleCall_4_2_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class OpenDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.OpenData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOpenDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOpenDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUrlKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUrlAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cUrlEStringParserRuleCall_4_2_0 = (RuleCall)cUrlAssignment_4_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//OpenData dataanalytics::OpenData:
		//	{dataanalytics::OpenData}
		//	'openData' name=EString '[' ('url' ':' url=EString)? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::OpenData} 'openData' name=EString '[' ('url' ':' url=EString)? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::OpenData}
		public Action getOpenDataAction_0() { return cOpenDataAction_0; }
		
		//'openData'
		public Keyword getOpenDataKeyword_1() { return cOpenDataKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//('url' ':' url=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'url'
		public Keyword getUrlKeyword_4_0() { return cUrlKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//url=EString
		public Assignment getUrlAssignment_4_2() { return cUrlAssignment_4_2; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_4_2_0() { return cUrlEStringParserRuleCall_4_2_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class ProvidedDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.ProvidedData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProvidedDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProvidedDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cProviderAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final CrossReference cProviderStakeholderCrossReference_3_0_0 = (CrossReference)cProviderAssignment_3_0.eContents().get(0);
		private final RuleCall cProviderStakeholderEStringParserRuleCall_3_0_0_1 = (RuleCall)cProviderStakeholderCrossReference_3_0_0.eContents().get(1);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cProviderAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final CrossReference cProviderStakeholderCrossReference_3_1_1_0 = (CrossReference)cProviderAssignment_3_1_1.eContents().get(0);
		private final RuleCall cProviderStakeholderEStringParserRuleCall_3_1_1_0_1 = (RuleCall)cProviderStakeholderCrossReference_3_1_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ProvidedData dataanalytics::ProvidedData:
		//	{dataanalytics::ProvidedData}
		//	'providedData'
		//	'{' (provider+=[stakeholder::Stakeholder|EString] ("," provider+=[stakeholder::Stakeholder|EString])*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::ProvidedData} 'providedData' '{' (provider+=[stakeholder::Stakeholder|EString] (","
		//provider+=[stakeholder::Stakeholder|EString])*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::ProvidedData}
		public Action getProvidedDataAction_0() { return cProvidedDataAction_0; }
		
		//'providedData'
		public Keyword getProvidedDataKeyword_1() { return cProvidedDataKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(provider+=[stakeholder::Stakeholder|EString] ("," provider+=[stakeholder::Stakeholder|EString])*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//provider+=[stakeholder::Stakeholder|EString]
		public Assignment getProviderAssignment_3_0() { return cProviderAssignment_3_0; }
		
		//[stakeholder::Stakeholder|EString]
		public CrossReference getProviderStakeholderCrossReference_3_0_0() { return cProviderStakeholderCrossReference_3_0_0; }
		
		//EString
		public RuleCall getProviderStakeholderEStringParserRuleCall_3_0_0_1() { return cProviderStakeholderEStringParserRuleCall_3_0_0_1; }
		
		//("," provider+=[stakeholder::Stakeholder|EString])*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }
		
		//provider+=[stakeholder::Stakeholder|EString]
		public Assignment getProviderAssignment_3_1_1() { return cProviderAssignment_3_1_1; }
		
		//[stakeholder::Stakeholder|EString]
		public CrossReference getProviderStakeholderCrossReference_3_1_1_0() { return cProviderStakeholderCrossReference_3_1_1_0; }
		
		//EString
		public RuleCall getProviderStakeholderEStringParserRuleCall_3_1_1_0_1() { return cProviderStakeholderEStringParserRuleCall_3_1_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class StakeholderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.Stakeholder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStakeholderAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOrganizationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOrganizationNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOrganizationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOrganizationEStringParserRuleCall_3_1_0 = (RuleCall)cOrganizationAssignment_3_1.eContents().get(0);
		
		//Stakeholder stakeholder::Stakeholder:
		//	{stakeholder::Stakeholder}
		//	//	'stakeholder'
		//	'organization' name=EString ('organizationName' organization=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{stakeholder::Stakeholder} //	'stakeholder'
		//'organization' name=EString ('organizationName' organization=EString)?
		public Group getGroup() { return cGroup; }
		
		//{stakeholder::Stakeholder}
		public Action getStakeholderAction_0() { return cStakeholderAction_0; }
		
		////	'stakeholder'
		//'organization'
		public Keyword getOrganizationKeyword_1() { return cOrganizationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('organizationName' organization=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'organizationName'
		public Keyword getOrganizationNameKeyword_3_0() { return cOrganizationNameKeyword_3_0; }
		
		//organization=EString
		public Assignment getOrganizationAssignment_3_1() { return cOrganizationAssignment_3_1; }
		
		//EString
		public RuleCall getOrganizationEStringParserRuleCall_3_1_0() { return cOrganizationEStringParserRuleCall_3_1_0; }
	}
	public class RealValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.RealValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRealValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRealKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEDoubleParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUnitAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUnitEStringParserRuleCall_6_0 = (RuleCall)cUnitAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSrcAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cSrcSourceCrossReference_9_0 = (CrossReference)cSrcAssignment_9.eContents().get(0);
		private final RuleCall cSrcSourceEStringParserRuleCall_9_0_1 = (RuleCall)cSrcSourceCrossReference_9_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//RealValue dataanalytics::RealValue:
		//	{dataanalytics::RealValue}
		//	'real' name=EString '=' value=EDouble '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::RealValue} 'real' name=EString '=' value=EDouble '(' unit=EString? ')' '['
		//src=[dataanalytics::Source|EString]? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::RealValue}
		public Action getRealValueAction_0() { return cRealValueAction_0; }
		
		//'real'
		public Keyword getRealKeyword_1() { return cRealKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EDouble
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_4_0() { return cValueEDoubleParserRuleCall_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//unit=EString?
		public Assignment getUnitAssignment_6() { return cUnitAssignment_6; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_6_0() { return cUnitEStringParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8() { return cLeftSquareBracketKeyword_8; }
		
		//src=[dataanalytics::Source|EString]?
		public Assignment getSrcAssignment_9() { return cSrcAssignment_9; }
		
		//[dataanalytics::Source|EString]
		public CrossReference getSrcSourceCrossReference_9_0() { return cSrcSourceCrossReference_9_0; }
		
		//EString
		public RuleCall getSrcSourceEStringParserRuleCall_9_0_1() { return cSrcSourceEStringParserRuleCall_9_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class BoolValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.BoolValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEBooleanParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUnitAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUnitEStringParserRuleCall_6_0 = (RuleCall)cUnitAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSrcAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cSrcSourceCrossReference_9_0 = (CrossReference)cSrcAssignment_9.eContents().get(0);
		private final RuleCall cSrcSourceEStringParserRuleCall_9_0_1 = (RuleCall)cSrcSourceCrossReference_9_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//BoolValue dataanalytics::BoolValue:
		//	{dataanalytics::BoolValue}
		//	'bool' name=EString '=' value=EBoolean '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::BoolValue} 'bool' name=EString '=' value=EBoolean '(' unit=EString? ')' '['
		//src=[dataanalytics::Source|EString]? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::BoolValue}
		public Action getBoolValueAction_0() { return cBoolValueAction_0; }
		
		//'bool'
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EBoolean
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_4_0() { return cValueEBooleanParserRuleCall_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//unit=EString?
		public Assignment getUnitAssignment_6() { return cUnitAssignment_6; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_6_0() { return cUnitEStringParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8() { return cLeftSquareBracketKeyword_8; }
		
		//src=[dataanalytics::Source|EString]?
		public Assignment getSrcAssignment_9() { return cSrcAssignment_9; }
		
		//[dataanalytics::Source|EString]
		public CrossReference getSrcSourceCrossReference_9_0() { return cSrcSourceCrossReference_9_0; }
		
		//EString
		public RuleCall getSrcSourceEStringParserRuleCall_9_0_1() { return cSrcSourceEStringParserRuleCall_9_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class IntegerValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.IntegerValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEIntParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUnitAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUnitEStringParserRuleCall_6_0 = (RuleCall)cUnitAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSrcAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cSrcSourceCrossReference_9_0 = (CrossReference)cSrcAssignment_9.eContents().get(0);
		private final RuleCall cSrcSourceEStringParserRuleCall_9_0_1 = (RuleCall)cSrcSourceCrossReference_9_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//IntegerValue dataanalytics::IntegerValue:
		//	{dataanalytics::IntegerValue}
		//	'int' name=EString '=' value=EInt '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataanalytics::IntegerValue} 'int' name=EString '=' value=EInt '(' unit=EString? ')' '['
		//src=[dataanalytics::Source|EString]? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataanalytics::IntegerValue}
		public Action getIntegerValueAction_0() { return cIntegerValueAction_0; }
		
		//'int'
		public Keyword getIntKeyword_1() { return cIntKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EInt
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_4_0() { return cValueEIntParserRuleCall_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//unit=EString?
		public Assignment getUnitAssignment_6() { return cUnitAssignment_6; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_6_0() { return cUnitEStringParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8() { return cLeftSquareBracketKeyword_8; }
		
		//src=[dataanalytics::Source|EString]?
		public Assignment getSrcAssignment_9() { return cSrcAssignment_9; }
		
		//[dataanalytics::Source|EString]
		public CrossReference getSrcSourceCrossReference_9_0() { return cSrcSourceCrossReference_9_0; }
		
		//EString
		public RuleCall getSrcSourceEStringParserRuleCall_9_0_1() { return cSrcSourceEStringParserRuleCall_9_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E' | 'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class InfrastructureComponent_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.InfrastructureComponent_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInfrastructureComponentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInfrastructureComponentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//InfrastructureComponent_Impl infrastructure::InfrastructureComponent:
		//	{infrastructure::InfrastructureComponent}
		//	'infrastructureComponent'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{infrastructure::InfrastructureComponent} 'infrastructureComponent' name=EString
		public Group getGroup() { return cGroup; }
		
		//{infrastructure::InfrastructureComponent}
		public Action getInfrastructureComponentAction_0() { return cInfrastructureComponentAction_0; }
		
		//'infrastructureComponent'
		public Keyword getInfrastructureComponentKeyword_1() { return cInfrastructureComponentKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class MonitoringInfrastructureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.MonitoringInfrastructure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMonitoringInfrastructureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMonitoringInfrastructureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cDevicesAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cDevicesIoTDevParserRuleCall_4_0_0 = (RuleCall)cDevicesAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cDevicesAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cDevicesIoTDevParserRuleCall_4_1_1_0 = (RuleCall)cDevicesAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//MonitoringInfrastructure infrastructure::MonitoringInfrastructure:
		//	{infrastructure::MonitoringInfrastructure}
		//	'monitoringInfrastructure'
		//	name=EString
		//	'{' (devices+=IoTDev ("," devices+=IoTDev)*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{infrastructure::MonitoringInfrastructure} 'monitoringInfrastructure' name=EString '{' (devices+=IoTDev (","
		//devices+=IoTDev)*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{infrastructure::MonitoringInfrastructure}
		public Action getMonitoringInfrastructureAction_0() { return cMonitoringInfrastructureAction_0; }
		
		//'monitoringInfrastructure'
		public Keyword getMonitoringInfrastructureKeyword_1() { return cMonitoringInfrastructureKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(devices+=IoTDev ("," devices+=IoTDev)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//devices+=IoTDev
		public Assignment getDevicesAssignment_4_0() { return cDevicesAssignment_4_0; }
		
		//IoTDev
		public RuleCall getDevicesIoTDevParserRuleCall_4_0_0() { return cDevicesIoTDevParserRuleCall_4_0_0; }
		
		//("," devices+=IoTDev)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//devices+=IoTDev
		public Assignment getDevicesAssignment_4_1_1() { return cDevicesAssignment_4_1_1; }
		
		//IoTDev
		public RuleCall getDevicesIoTDevParserRuleCall_4_1_1_0() { return cDevicesIoTDevParserRuleCall_4_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.Sensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cModelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cModelEStringParserRuleCall_2_0 = (RuleCall)cModelAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLocationKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cEqualsSignKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cLocationAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cLocationEStringParserRuleCall_3_3_0 = (RuleCall)cLocationAssignment_3_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		
		//Sensor infrastructure::Sensor:
		//	{infrastructure::Sensor}
		//	'sensor' model=EString? ('[' 'location' '=' location=EString ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{infrastructure::Sensor} 'sensor' model=EString? ('[' 'location' '=' location=EString ']')?
		public Group getGroup() { return cGroup; }
		
		//{infrastructure::Sensor}
		public Action getSensorAction_0() { return cSensorAction_0; }
		
		//'sensor'
		public Keyword getSensorKeyword_1() { return cSensorKeyword_1; }
		
		//model=EString?
		public Assignment getModelAssignment_2() { return cModelAssignment_2; }
		
		//EString
		public RuleCall getModelEStringParserRuleCall_2_0() { return cModelEStringParserRuleCall_2_0; }
		
		//('[' 'location' '=' location=EString ']')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }
		
		//'location'
		public Keyword getLocationKeyword_3_1() { return cLocationKeyword_3_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_2() { return cEqualsSignKeyword_3_2; }
		
		//location=EString
		public Assignment getLocationAssignment_3_3() { return cLocationAssignment_3_3; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_3_3_0() { return cLocationEStringParserRuleCall_3_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }
	}
	public class ActuatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smartcity.project.xtext.SmartCityDSL.Actuator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActuatorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActuatorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cModelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cModelEStringParserRuleCall_2_0 = (RuleCall)cModelAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLocationKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cEqualsSignKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cLocationAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cLocationEStringParserRuleCall_3_3_0 = (RuleCall)cLocationAssignment_3_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		
		//Actuator infrastructure::Actuator:
		//	{infrastructure::Actuator}
		//	'actuator' model=EString? ('[' 'location' '=' location=EString ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{infrastructure::Actuator} 'actuator' model=EString? ('[' 'location' '=' location=EString ']')?
		public Group getGroup() { return cGroup; }
		
		//{infrastructure::Actuator}
		public Action getActuatorAction_0() { return cActuatorAction_0; }
		
		//'actuator'
		public Keyword getActuatorKeyword_1() { return cActuatorKeyword_1; }
		
		//model=EString?
		public Assignment getModelAssignment_2() { return cModelAssignment_2; }
		
		//EString
		public RuleCall getModelEStringParserRuleCall_2_0() { return cModelEStringParserRuleCall_2_0; }
		
		//('[' 'location' '=' location=EString ']')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }
		
		//'location'
		public Keyword getLocationKeyword_3_1() { return cLocationKeyword_3_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_2() { return cEqualsSignKeyword_3_2; }
		
		//location=EString
		public Assignment getLocationAssignment_3_3() { return cLocationAssignment_3_3; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_3_3_0() { return cLocationEStringParserRuleCall_3_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }
	}
	
	
	private final SmartCityModelElements pSmartCityModel;
	private final SourceElements pSource;
	private final DataElements pData;
	private final InfrastructureComponentElements pInfrastructureComponent;
	private final IoTDevElements pIoTDev;
	private final SmartCityElements pSmartCity;
	private final EStringElements pEString;
	private final DataPackageElements pDataPackage;
	private final PublicInfrastructureLayerElements pPublicInfrastructureLayer;
	private final SocialMediaElements pSocialMedia;
	private final OpenDataElements pOpenData;
	private final ProvidedDataElements pProvidedData;
	private final StakeholderElements pStakeholder;
	private final RealValueElements pRealValue;
	private final BoolValueElements pBoolValue;
	private final IntegerValueElements pIntegerValue;
	private final EDoubleElements pEDouble;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final InfrastructureComponent_ImplElements pInfrastructureComponent_Impl;
	private final MonitoringInfrastructureElements pMonitoringInfrastructure;
	private final SensorElements pSensor;
	private final ActuatorElements pActuator;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmartCityDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSmartCityModel = new SmartCityModelElements();
		this.pSource = new SourceElements();
		this.pData = new DataElements();
		this.pInfrastructureComponent = new InfrastructureComponentElements();
		this.pIoTDev = new IoTDevElements();
		this.pSmartCity = new SmartCityElements();
		this.pEString = new EStringElements();
		this.pDataPackage = new DataPackageElements();
		this.pPublicInfrastructureLayer = new PublicInfrastructureLayerElements();
		this.pSocialMedia = new SocialMediaElements();
		this.pOpenData = new OpenDataElements();
		this.pProvidedData = new ProvidedDataElements();
		this.pStakeholder = new StakeholderElements();
		this.pRealValue = new RealValueElements();
		this.pBoolValue = new BoolValueElements();
		this.pIntegerValue = new IntegerValueElements();
		this.pEDouble = new EDoubleElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pInfrastructureComponent_Impl = new InfrastructureComponent_ImplElements();
		this.pMonitoringInfrastructure = new MonitoringInfrastructureElements();
		this.pSensor = new SensorElements();
		this.pActuator = new ActuatorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("smartcity.project.xtext.SmartCityDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////import "http://cs.gssi.it/smartcity/stakeholder" as stakeholder
	////import "http://cs.gssi.it/smartcity/infrastructure" as infrastructure
	////import "http://cs.gssi.it/smartcity" as smartcity
	//SmartCityModel smartcity::SmartCityModel:
	//	{smartcity::SmartCityModel} ('smartCities' '{' smartCities+=SmartCity ("," smartCities+=SmartCity)* '}')?;
	public SmartCityModelElements getSmartCityModelAccess() {
		return pSmartCityModel;
	}
	
	public ParserRule getSmartCityModelRule() {
		return getSmartCityModelAccess().getRule();
	}
	
	//Source dataanalytics::Source:
	//	SocialMedia | OpenData | ProvidedData | Stakeholder;
	public SourceElements getSourceAccess() {
		return pSource;
	}
	
	public ParserRule getSourceRule() {
		return getSourceAccess().getRule();
	}
	
	//Data dataanalytics::Data:
	//	RealValue | BoolValue | IntegerValue;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//InfrastructureComponent infrastructure::InfrastructureComponent:
	//	InfrastructureComponent_Impl | MonitoringInfrastructure;
	public InfrastructureComponentElements getInfrastructureComponentAccess() {
		return pInfrastructureComponent;
	}
	
	public ParserRule getInfrastructureComponentRule() {
		return getInfrastructureComponentAccess().getRule();
	}
	
	//IoTDev infrastructure::IoTDev:
	//	Sensor | Actuator;
	public IoTDevElements getIoTDevAccess() {
		return pIoTDev;
	}
	
	public ParserRule getIoTDevRule() {
		return getIoTDevAccess().getRule();
	}
	
	//SmartCity smartcity::SmartCity:
	//	{smartcity::SmartCity} ('city' city=EString)?
	//	'{' ('stakeholders' '{' stakeholders+=Source ("," stakeholders+=Source)* '}')? ('data' '{' data+=DataPackage (","
	//	data+=DataPackage)* '}')? ('infrastructurelayer' infrastructurelayer=PublicInfrastructureLayer)?
	//	'}';
	public SmartCityElements getSmartCityAccess() {
		return pSmartCity;
	}
	
	public ParserRule getSmartCityRule() {
		return getSmartCityAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//DataPackage dataanalytics::DataPackage:
	//	{dataanalytics::DataPackage}
	//	'dataPackage'
	//	name=EString
	//	'{' (data+=Data ("," data+=Data)*)?
	//	'}';
	public DataPackageElements getDataPackageAccess() {
		return pDataPackage;
	}
	
	public ParserRule getDataPackageRule() {
		return getDataPackageAccess().getRule();
	}
	
	//PublicInfrastructureLayer infrastructure::PublicInfrastructureLayer:
	//	{infrastructure::PublicInfrastructureLayer} name=EString
	//	'{' ('components' '{' components+=InfrastructureComponent ("," components+=InfrastructureComponent)* '}')?
	//	'}';
	public PublicInfrastructureLayerElements getPublicInfrastructureLayerAccess() {
		return pPublicInfrastructureLayer;
	}
	
	public ParserRule getPublicInfrastructureLayerRule() {
		return getPublicInfrastructureLayerAccess().getRule();
	}
	
	//SocialMedia dataanalytics::SocialMedia:
	//	{dataanalytics::SocialMedia}
	//	'socialMedia' name=EString '[' ('url' ':' url=EString)? ']';
	public SocialMediaElements getSocialMediaAccess() {
		return pSocialMedia;
	}
	
	public ParserRule getSocialMediaRule() {
		return getSocialMediaAccess().getRule();
	}
	
	//OpenData dataanalytics::OpenData:
	//	{dataanalytics::OpenData}
	//	'openData' name=EString '[' ('url' ':' url=EString)? ']';
	public OpenDataElements getOpenDataAccess() {
		return pOpenData;
	}
	
	public ParserRule getOpenDataRule() {
		return getOpenDataAccess().getRule();
	}
	
	//ProvidedData dataanalytics::ProvidedData:
	//	{dataanalytics::ProvidedData}
	//	'providedData'
	//	'{' (provider+=[stakeholder::Stakeholder|EString] ("," provider+=[stakeholder::Stakeholder|EString])*)?
	//	'}';
	public ProvidedDataElements getProvidedDataAccess() {
		return pProvidedData;
	}
	
	public ParserRule getProvidedDataRule() {
		return getProvidedDataAccess().getRule();
	}
	
	//Stakeholder stakeholder::Stakeholder:
	//	{stakeholder::Stakeholder}
	//	//	'stakeholder'
	//	'organization' name=EString ('organizationName' organization=EString)?;
	public StakeholderElements getStakeholderAccess() {
		return pStakeholder;
	}
	
	public ParserRule getStakeholderRule() {
		return getStakeholderAccess().getRule();
	}
	
	//RealValue dataanalytics::RealValue:
	//	{dataanalytics::RealValue}
	//	'real' name=EString '=' value=EDouble '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
	public RealValueElements getRealValueAccess() {
		return pRealValue;
	}
	
	public ParserRule getRealValueRule() {
		return getRealValueAccess().getRule();
	}
	
	//BoolValue dataanalytics::BoolValue:
	//	{dataanalytics::BoolValue}
	//	'bool' name=EString '=' value=EBoolean '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
	public BoolValueElements getBoolValueAccess() {
		return pBoolValue;
	}
	
	public ParserRule getBoolValueRule() {
		return getBoolValueAccess().getRule();
	}
	
	//IntegerValue dataanalytics::IntegerValue:
	//	{dataanalytics::IntegerValue}
	//	'int' name=EString '=' value=EInt '(' unit=EString? ')' '[' src=[dataanalytics::Source|EString]? ']';
	public IntegerValueElements getIntegerValueAccess() {
		return pIntegerValue;
	}
	
	public ParserRule getIntegerValueRule() {
		return getIntegerValueAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//InfrastructureComponent_Impl infrastructure::InfrastructureComponent:
	//	{infrastructure::InfrastructureComponent}
	//	'infrastructureComponent'
	//	name=EString;
	public InfrastructureComponent_ImplElements getInfrastructureComponent_ImplAccess() {
		return pInfrastructureComponent_Impl;
	}
	
	public ParserRule getInfrastructureComponent_ImplRule() {
		return getInfrastructureComponent_ImplAccess().getRule();
	}
	
	//MonitoringInfrastructure infrastructure::MonitoringInfrastructure:
	//	{infrastructure::MonitoringInfrastructure}
	//	'monitoringInfrastructure'
	//	name=EString
	//	'{' (devices+=IoTDev ("," devices+=IoTDev)*)?
	//	'}';
	public MonitoringInfrastructureElements getMonitoringInfrastructureAccess() {
		return pMonitoringInfrastructure;
	}
	
	public ParserRule getMonitoringInfrastructureRule() {
		return getMonitoringInfrastructureAccess().getRule();
	}
	
	//Sensor infrastructure::Sensor:
	//	{infrastructure::Sensor}
	//	'sensor' model=EString? ('[' 'location' '=' location=EString ']')?;
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//Actuator infrastructure::Actuator:
	//	{infrastructure::Actuator}
	//	'actuator' model=EString? ('[' 'location' '=' location=EString ']')?;
	public ActuatorElements getActuatorAccess() {
		return pActuator;
	}
	
	public ParserRule getActuatorRule() {
		return getActuatorAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
